library(plyr)
args <- commandArgs(TRUE)
df<-read.delim(args[1],header=F)
a<-ddply(df, .(V5), summarise, test = list(V2), test1 = list(V3), test2 = list(V1), test3 = list(V6), test4 = list(V4))
a1<-lapply(a$test, `[[`, 1)
a2<-lapply(a$test1, tail, n = 1L)
a3<-lapply(a$test2, `[[`, 1)
a4<-lapply(a$test3, `[[`, 1)
a5<-lapply(a$test4, `[[`, 1)
d1<-paste(unlist(a3),unlist(a5),a1,a2,a$V5,sep = ",")
e<-c()
for (t in 1:length(a4)) { e<-paste(e,a4[[t]],sep="#") }
s <- strsplit(e, split = "#")
s1<-s[[1]][-1]
s2 <- data.frame(matrix(unlist(s1), byrow=T))
d11 <- data.frame(matrix(unlist(d1), byrow=T))
colnames(d11) <- c("chromosome,strand,start,end,transcript_id")
colnames(s2) <- c("genename")
d12<-cbind(d11,s2)
write.csv(d12,quote=F,row.names=F,"merged-cols1.csv")